# Generated by Django 6.0.5 on 2026-05-16 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('model', models.CharField(max_length=200, verbose_name='Modelo')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Número de Série')),
                ('manufacturer', models.CharField(max_length=200, verbose_name='Fabricante')),
                ('location', models.CharField(max_length=200, verbose_name='Localização')),
                ('status', models.CharField(choices=[('available', 'Disponível'), ('in_use', 'Em Uso'), ('maintenance', 'Em Manutenção'), ('broken', 'Com Defeito'), ('inactive', 'Inativo')], default='available', max_length=20, verbose_name='Status')),
                ('acquisition_date', models.DateField(blank=True, null=True, verbose_name='Data de Aquisição')),
                ('maintenance_date', models.DateField(blank=True, null=True, verbose_name='Próxima Manutenção')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('manual', models.FileField(blank=True, null=True, upload_to='manuals/', verbose_name='Manual')),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipments/', verbose_name='Foto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descrição da Falha')),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False, verbose_name='Resolvido')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolvido em')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failures', to='equipments.equipment', verbose_name='Equipamento')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Reportado por')),
            ],
            options={
                'verbose_name': 'Falha de Equipamento',
                'ordering': ['-reported_at'],
            },
        ),
    ]
