# Generated by Django 6.0.5 on 2026-05-16 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipments', '0001_initial'),
        ('experiments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('absorbance', 'Absorbância'), ('enzymatic_activity', 'Atividade Enzimática'), ('microbial_growth', 'Crescimento Microbiano'), ('concentration', 'Concentração'), ('chromatogram', 'Cromatograma'), ('microscopy', 'Microscopia'), ('pcr', 'PCR'), ('sequencing', 'Sequenciamento'), ('other', 'Outro')], max_length=50, verbose_name='Tipo de Análise')),
                ('name', models.CharField(max_length=200, verbose_name='Nome/Identificação')),
                ('description', models.TextField(blank=True, verbose_name='Descrição Técnica')),
                ('numeric_result', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Resultado Numérico')),
                ('result_unit', models.CharField(blank=True, max_length=50, verbose_name='Unidade do Resultado')),
                ('result_file', models.FileField(blank=True, null=True, upload_to='analysis/', verbose_name='Arquivo de Resultado')),
                ('result_image', models.ImageField(blank=True, null=True, upload_to='analysis/images/', verbose_name='Imagem do Resultado')),
                ('observations', models.TextField(blank=True, verbose_name='Observações Técnicas')),
                ('analysis_date', models.DateField(verbose_name='Data da Análise')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analyst', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Analista')),
                ('equipment_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipments.equipment', verbose_name='Equipamento Utilizado')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='experiments.experiment', verbose_name='Experimento')),
            ],
            options={
                'verbose_name': 'Análise',
                'verbose_name_plural': 'Análises',
                'ordering': ['-analysis_date'],
            },
        ),
    ]
