# Generated by Django 6.0.5 on 2026-05-16 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiments', '0001_initial'),
        ('reagents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('entry', 'Entrada'), ('exit', 'Saída'), ('adjustment', 'Ajuste'), ('loss', 'Descarte')], max_length=20, verbose_name='Tipo')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade')),
                ('previous_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade Anterior')),
                ('new_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Nova Quantidade')),
                ('reason', models.TextField(blank=True, verbose_name='Motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='experiments.experiment', verbose_name='Experimento Associado')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
                ('reagent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='reagents.reagent', verbose_name='Reagente')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-created_at'],
            },
        ),
    ]
