# Generated by Django 6.0.5 on 2026-05-16 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reagent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('category', models.CharField(choices=[('solvent', 'Solvente'), ('acid', 'Ácido'), ('base', 'Base'), ('salt', 'Sal'), ('buffer', 'Tampão'), ('enzyme', 'Enzima'), ('antibody', 'Anticorpo'), ('culture_media', 'Meio de Cultura'), ('dye', 'Corante'), ('other', 'Outro')], max_length=50, verbose_name='Categoria')),
                ('manufacturer', models.CharField(max_length=200, verbose_name='Fabricante')),
                ('lot', models.CharField(max_length=100, verbose_name='Lote')),
                ('expiration_date', models.DateField(verbose_name='Data de Validade')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade')),
                ('unit', models.CharField(max_length=20, verbose_name='Unidade')),
                ('supplier', models.CharField(max_length=200, verbose_name='Fornecedor')),
                ('location', models.CharField(max_length=200, verbose_name='Localização')),
                ('cas_number', models.CharField(blank=True, max_length=50, verbose_name='Número CAS')),
                ('safety_notes', models.TextField(blank=True, verbose_name='Notas de Segurança')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado por')),
            ],
            options={
                'verbose_name': 'Reagente',
                'verbose_name_plural': 'Reagentes',
                'ordering': ['name'],
            },
        ),
    ]
